# Generated by Django 4.2.4 on 2023-11-28 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=700)),
                ("hints", models.CharField(default="", max_length=700)),
                ("longitude", models.DecimalField(decimal_places=15, max_digits=18)),
                ("latitude", models.DecimalField(decimal_places=15, max_digits=18)),
                ("approved", models.BooleanField()),
                ("point_value", models.IntegerField(default=50)),
                (
                    "bundle",
                    models.CharField(
                        choices=[
                            ("E-Way", "E-Way"),
                            ("Food", "Food"),
                            ("Dorms", "Dorms"),
                            ("Visit", "Spots to Visit"),
                            ("Mystery", "Mystery"),
                        ],
                        default="E-Way",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserClueScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("solved", models.BooleanField(default=False)),
                ("attempts_left", models.IntegerField(default=5)),
                (
                    "clue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hooshunt.clue"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
