# Generated by Django 4.2.5 on 2023-12-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooshunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='bundle',
            field=models.CharField(choices=[('E-Way', 'E-Way'), ('Food', 'Food'), ('Dorms', 'Dorms'), ('Spots to Visit', 'Spots to Visit'), ('Mystery', 'Mystery')], default='E-Way', max_length=200),
        ),
    ]
