# Generated by Django 4.2.5 on 2023-12-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('admin', 'admin'), ('regular', 'regular')], default='regular', max_length=255),
        ),
    ]
